spring:
  datasource:
    url: jdbc:mysql://1.94.109.12:3306/employment_infomation
    username: root
    password: xxs@2024
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 2334


#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/xml/*.xml




