services:
  employment:
    image: employment:1.0
    container_name: myapp
    restart: always
    ports:
      - 2334:2334
    volumes:
      - "./app/config:/data/docker-data/employment/config"
      - "./app/static:/data/docker-data/employment/data"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=Asia/Shanghai"
      - "TAKE_FILE_OWNERSHIP=true"   #volumes 挂载权限 如果不想要挂载es文件改配置可以删除
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1